language: node_js
node_js: '0.10'

addons:
  sauce_connect: true

cache:
  directories:
  - node_modules
  - bower_components

before_install:
- npm install -g grunt-cli bower --production
- bower install

env:
  global:
  - secure: Dvv2FqDqWdvqyNxZ2RFn75JLZLbIcXoialla3Dxn4ikTVQ57TWrz40j65EWxJliGa8+a4MK2msqtZEm3+zbNa0iV/cOfxvBtHM6O0MbaneVQwtFKtQsptfwTHppizk52E6FSPNEb+rsHThyGcwP66mksq06inGS9UGEFlxI+X7Y=
  - secure: HtaQh9PNw+2fyLkF9Sf52BoswncG4E639yN1JSYqHHZ+GwAn9C3UC6WK/MzSl9iPDGiTBmebI6Xj5r30Tp573BzwJ7XhnAnwbsEpdUCpVP9kqqZrkP0KJyZ0YQqlyW1//ustgxP98D47Mb0DCfBvC6/zIora5LmvQTCrZJudCBU=
